from cefpython3 import cefpython as cef

# CEFを初期化する
cef.Initialize()

# CEFのバージョン情報を取得する
version_info = cef.GetVersion()

# バージョン情報を表示する
print("CEF Version:", version_info["cef_version"])
print("Chromium Version:", version_info["chromium_version"])
print("CEF Commit Hash:", version_info["cef_commit_hash"])

# CEFを終了する
cef.Shutdown()
