<TextEditingOperation>:
    BoxLayout:
        orientation: 'horizontal'
        
        # 左側のレイアウト
        BoxLayout:
            orientation: 'vertical'
            size_hint_x: 0.9
            
            # 統計情報を表示するラベル
            Label:
                id: stats_label
                text: root.stats_label.text
                font_size: 24
                size_hint_y: None
                height: 40
            
            # 日本語のIME入力に対応するテキスト入力
            JapaneseTextInput:
                id: text_input
                text: ''
                size_hint_y: None
                height: 600
                multiline: True
                on_focus: root.on_text_input_focus(*args)

            # コントロールボタンのレイアウト
            BoxLayout:
                orientation: 'horizontal'
                size_hint_y: None
                height: 50

                Button:
                    text: '新規作成'
                    on_press: root.new_file()

                Button:
                    text: '開く'

                Button:
                    text: '名付けて保存'

                Button:
                    text: '保存'

                Button:
                    text: 'コピー'
                    on_press: root.copy_text()

                Button:
                    text: 'ペースト'
                    on_press: root.paste_text()

                Button:
                    text: 'クリア'
                    on_press: root.clear_text()

                Button:
                    text: '前挿入'
                    on_press: root.insert_text_at_line_start()

                Button:
                    text: '両端挿入'
                    on_press: root.wrap_text_in_brackets()

                Button:
                    text: '後挿入'
                    on_press: root.insert_text_at_line_end()

            # フォントサイズスライダーとストップウォッチのレイアウト
            BoxLayout:
                orientation: 'horizontal'
                size_hint_y: None
                height: 50

                Slider:
                    min: 10
                    max: 32
                    step: 2
                    value: 14
                    size_hint_x: 0.5
                    on_value: root.adjust_font_size(self.value)

                Label:
                    id: stopwatch_label
                    text: "00:00,00.00"
                    font_size: 24
                    size_hint_x: 0.2

                Button:
                    id: stopwatch_button
                    text: '開始'
                    size_hint_x: 0.1
                    height: 50
                    on_press: root.toggle_stopwatch()

                Button:
                    text: 'リセット'
                    size_hint_x: 0.1
                    on_press: root.reset_stopwatch()

                ToggleButton:
                    id: always_on_top_button
                    text: 'off'
                    size_hint_x: 0.1
                    on_press: root.toggle_always_on_top(self)

        # 右側のレイアウト
        BoxLayout:
            orientation: 'vertical'
            size_hint_x: 0.1
            
            # ノードスクロールビュー
            ScrollView:
                id: node_scroll_view
                size_hint: (1, None)
                size: (400, Window.height - 50)
                
                GridLayout:
                    id: node_layout
                    cols: 1
                    size_hint_y: None
                    spacing: 0
                    on_minimum_height: node_layout.height = self.minimum_height
            
            # 入力フォームと生成ボタンのレイアウト
            BoxLayout:
                orientation: 'vertical'
                size_hint_y: 0.3
                height: 40

                TextInput:
                    id: input_form
                    size_hint_y: None
                    height: 40
                    multiline: False

                ToggleButton:
                    id: generate_button
                    text: '生成'
                    height: 40
                    on_press: root.generate_text_button()

                Button:
                    id: clear_button
                    text: 'クリア'
                    height: 40
                    on_press: root.clear_input_form()

            # かっこボタンのレイアウト
            BoxLayout:
                id: bracket_buttons_layout
                orientation: 'vertical'
                size_hint_y: None
                height: 50
            
            # シンボルボタンのレイアウト
            BoxLayout:
                id: symbol_buttons_layout
                orientation: 'vertical'
                size_hint_y: None
                height: 50
