services:
  - type: web
    name: render-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: FLASK_DEBUG
        value: "0"
      - key: SECRET_KEY
        generateValue: true
